version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"     # RabbitMQ AMQP port
      - "15672:15672"   # RabbitMQ Management console port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia   # Persistent data storage
      - rabbitmq-logs:/var/log/rabbitmq          # Logs storage

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local