import axios from 'axios';
import { S3Client, CreateMultipartUploadCommand, UploadPartCommand, CompleteMultipartUploadCommand, AbortMultipartUploadCommand } from '@aws-sdk/client-s3';
import config from '../config/index.js';

const apiClient = axios.create({
    baseURL: config.API_BASE_URL,
});

/**
 * Retrieves a pre-signed PUT Url generated by the backend for uploading a file to S3.
 * @param {Object} params - Parameters for generating the signed URL (key, content_type).
 * @returns {Promise<Object>} - Object containing the presigned PUT Url.
 */
export async function getSignedUrl({ key, content_type }) {
    try {
      const response = await apiClient.post("/s3/upload/generate-signed-url", {
        key,
        content_type,
      });
      return response.data;
    } catch (error) {
      console.error("Error getting presigned PUT URL:", error);
      throw error; 
    }
  }

  /**
 * Notifies the backend about a successful file upload to S3 with the necessary metadata.
 * @param data - Metadata required for processing the file.
 * @returns {Promise<Object>} - Response from the backend.
 * @throws {Error} - Error if the request fails.
 * */
  export async function notifyClientUpload(data) {
    try {
      const response = await apiClient.post("/s3/upload/notify-client-upload", data, {
        headers: {
          'Content-Type': 'application/json', // Set content type to application/json
        },
      });
      return response.data;
    } catch (error) {
      console.error("Error notifying backend:", error);
      throw error;
    }
  }

  /**
 * Uploads a file to S3 using a pre-signed URL, with support for multipart upload for large files.
 * @param {string} key - The S3 object key (file name).
 * @param {string} signedUrl - The pre-signed URL for direct upload.
 * @param {File} file - The file to be uploaded.
 * @param {string} contentType - The MIME type of the file.
 * @param {Function} onProgress - Callback function to handle progress events.
 * @param {Function} onComplete - Callback function to handle completion events.
 * @returns {Promise<void>}
 */
  export async function uploadFileToS3SignedUrl(key, signedUrl, file, contentType, onProgress, onComplete) {
    const s3Client = new S3Client({ 
        region: config.AWS.Region,
        credentials: {
            accessKeyId: config.AWS.AccessKey,
            secretAccessKey: config.AWS.SecretAccessKey,
        },
    });

    const bucketName = config.AWS.BucketName;
    
    try {
        if (file.size <= 100 * 1024 * 1024) { // Small file threshold: 100MB
            
          // Direct upload for small files
          await axios.put(signedUrl, file, {
              onUploadProgress: onProgress,
              headers: {
                "Content-Type": contentType,
              },
          });

          if (typeof onComplete === 'function') {
            onComplete({ status: 'File uploaded successfully' });
          }

      } else {

        // Multipart upload for large files
        let uploadId;

        try {
            // Initialize multipart upload
            const multipartUpload = await s3Client.send(new CreateMultipartUploadCommand({
                Bucket: bucketName,
                Key: key,
                ContentType: contentType,
            }));

            uploadId = multipartUpload.UploadId;

            const partSize = 5 * 1024 * 1024; // 5MB parts
            const numParts = Math.ceil(file.size / partSize);
            const uploadPromises = [];

            for (let i = 0; i < numParts; i++) {
                const start = i * partSize;
                const end = Math.min(start + partSize, file.size);
                const part = file.slice(start, end);

                const partNumber = i + 1;
                const uploadPartCommand = new UploadPartCommand({
                    Bucket: bucketName,
                    Key: key,
                    UploadId: uploadId,
                    PartNumber: partNumber,
                    Body: part,
                });

                // Upload each part and track progress
                const uploadPromise = s3Client.send(uploadPartCommand)
                    .then((data) => ({
                        ETag: data.ETag,
                        PartNumber: partNumber,
                    }));
                uploadPromises.push(uploadPromise);
            }

            // Wait for all parts to upload
            const partsData = await Promise.all(uploadPromises);

            // Complete multipart upload
            await s3Client.send(new CompleteMultipartUploadCommand({
                Bucket: bucketName,
                Key: key,
                UploadId: uploadId,
                MultipartUpload: {
                    Parts: partsData,
                },
            }));

            if (typeof onComplete === 'function') {
                onComplete({ status: 'File uploaded successfully' });
              }
        } catch (err) {
            console.error('Error uploading file: ', err);

            // Abort multipart upload if an error occurs
            if (uploadId) {
                await s3Client.send(new AbortMultipartUploadCommand({
                    Bucket: bucketName,
                    Key: key,
                    UploadId: uploadId,
                }));
            }
        
            throw err; // Rethrow the error to handle it in the caller
        }
    }
  } catch (error) {
      console.error("Error uploading file:", error);
      throw error;
  }
}
